version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

    workflows:
      version: 2
      build:
        jobs:
          - build

